config/routes.rb
Rails.application.routes.draw do
  resources :questions
  root to: 'homes#index'
  resources :comments
  resources :articles
  resources :answers
  resources :money
  resources :homes
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answer

    validates :content, :name, presence: {message:'は、必須項目です。'}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order created_at: :desc
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
    @answer.question_id = params[:id]
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    redirect_to '/questions'
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to 'questions' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    redirect_to '/questions'
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    redirect_to '/questions'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :content, :name, :finished)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :finished %>
    <%= form.check_box :finished %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_form2.html.erb
<% if answer.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(answer.errors.count, "error") %>prohibited this answer from being saved:</h2>
        <ul>
        <% answer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<%= form_for(answer) do |f| %>
    <%= f.hidden_field :question_id, {value: answer.question_id} %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, rows:2, class:"form-control" %>
    </div>
    <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Questions</h1>

<table class="table mt-5 mb-5">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Name</th>
      <th>Finished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.finished ? '終了': '受付中' %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新たに質問する', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Question & Answer</h1>

<div class="jumbotron p-4 mb-4">
  <h1 class="card-title">
    <%= @question.title %>
  </h1>
  
  <p class="card-text">
    <%= @question.content %>
  </p>

  <h1 class="blockquote-footer text-right">
    <%= @question.name %>
  </h1>

  <div class="<%= @question.finished ? 'text-danger' : 'text-primary' %>">
    <%= @question.finished ? '終了' : '受付中' %>
  </div>
</div>


<% if @question.finished? == false then %>
  <div class="card p-3 mb-4">
    <h3 class="h4 text-primary">※回答する</h3>
    <%= render 'form2', answer: @answer %>
  </div>
<% end %>

<h3 class="h4 text-primary">※これまで寄せられた回答</h3>

<ul class="list-group">
<% if @question.answer.count == 0 then %>
  <p class="answer">※まだありません。</p>
<% else %>
  <% @question.answer.reverse_each do |re| %>
    <li class="list-group-item">
      <%= re.content + '(' + re.name + ')' %>
    </li>
  <% end %>
<% end %>
</ul>
<%= link_to 'トップページに戻る', questions_path %>